### ISSUE TITLE
Revise deprecation clause

### ISSUE THREAD

**Issue by hvr** [haskell/pvp#12]
# Current state

The 7th clause of the PVP currently states:

> *Deprecation*. Deprecated entities (via a `DEPRECATED` pragma) *SHOULD* be
counted as removed for the purposes of upgrading the API, because packages that
use `-Werror` will be broken by the deprecation. In other words the new *A.B*
**SHOULD** be greater than the previous *A.B*.

Quoting RFC2119:

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
>   may exist valid reasons in particular circumstances to ignore a
>   particular item, but the full implications must be understood and
>   carefully weighed before choosing a different course.

# Proposed change

Requiring a major version increment for deprecation seems overkill, as nowadays having `-Werror` enabled by default is rejected on Hackage uploads. Thereby the original rationale makes little sense, as a new deprecation annotation/warning does not cause compilation break, nor does it represent a semantic change. Hence a major version signal is not sensible.

"Recommend" only a minor version bump (so that the deprecation warning can be acted upon guarded by `MIN_VERSION_foo(a,b,c)` macros, which can only access the major+minor version components.

Suggested rewording:

> *Deprecation*. Deprecated entities (via a `DEPRECATED` pragma) *SHOULD* be counted as a *non-breaking change*. In other words, the new *A.B* **MAY** remain the same but the new *C* **SHOULD** be greater than the old *C*.

# History

This clause was added back in [2011-06-28](https://wiki.haskell.org/index.php?title=Package_versioning_policy&diff=40683&oldid=37378) and the change comment says merely

> discussion on #haskell suggested deprecation = removal

Going through the IRC logs, the conversation that lead to that change took place earlier on the same day (UTC+2 timestamps):

```
02:34 < benmachine> so guys, if I'm deprecating things in a module, what effect should that have on the version number of the next release?
02:35 < edwardk> removed functionality should cause the major version # to bump
02:35 < benmachine> sure, but it's not removed
02:36 < edwardk> the major version # are the x & y out of x.y.z.w
02:36 < benmachine> it's still there, but it just spits a warning if you use it
02:36 < dankna> I think deprecation ought to count as removal for that purpose, but I have no idea what the standard says
02:36 < benmachine> I mean deprecating as in the pragam
02:36 < identity_> what about minor API change?
02:36 < identity_> e.g. not backwards compatible change
02:36 < benmachine> dankna: the PVP page on the wiki doesn't know about the deprecate pragma
02:36 < dankna> I see
02:36 < tommd> benmachine: I don't think the PVP says anything, but I'd bump the C (in A.B.C.D versions)
02:36 < edwardk> i'd probably still bump the major version. the reason being that -Wall will crap out
02:36 < benmachine> edwardk: you mean -Werror?
02:37 < edwardk> and virtually everyone who builds on cabal builds with -Werror or -Wall
02:37 < edwardk> yeah
02:37 < aavogt> people widely use -Werror?
02:37 < benmachine> ho hum
02:37 < benmachine> I don't
02:37  * identity_ doesn't
02:37  * identity_ didn't know
02:37 < tommd> That's news to me
02:37 < edwardk> i use -Wall everywhere at least
02:37 < gfarfl> iwtu: actually, since Map.insert takes a key and a value, you need to change that to (uncurry insert (key,value))
02:37 < benmachine> enough people do that I'm inclined to agree with edwardk
02:38 < benmachine> which means I just screwed up :P oh well
02:38 < benmachine> (I released 0.4.0.1 with two things deprecated)
02:38 < benmachine> over 0.4
02:38 < benmachine> so auxiliary question: can I get a version "unreleased"?
02:39 < benmachine> almost certainly overkill in this case
02:39 < benmachine> but would be nice to know
```

**Comment by ekmett** [comment]
👍 from me at least.

**Comment by ezyang** [comment]
Seems fine.

**Comment by tfausak** [comment]
I agree. It doesn't make sense to me to make deprecations the same as removals. At that point, why deprecate at all? Just remove it and be done with it.

**Comment by eborden** [comment]
:+1:

**Comment by sol** [comment]
Same thought here!

**Comment by andrewthad** [comment]
+1 from me

**Comment by phadej** [comment]
on https://pvp.haskell.org/ it still says

> Deprecation. Deprecated entities (via a DEPRECATED pragma) SHOULD be counted as removed for the purposes of upgrading the API, because packages that use -Werror will be broken by the deprecation. In other words the new A.B SHOULD be greater than the previous A.B.

**Comment by jkachmar** [comment]
Ping. What's holding this up?

**Comment by m-renaud** [comment]
Friendly ping, this is still holding up https://github.com/tibbe/unordered-containers/pull/176, and it's been over a year now which means the new (consistent) API would have been the default now.

**Comment by eborden** [comment]
It looks like the necessary changes already exist in [PVP 1.1](https://github.com/haskell/pvp/blob/master/v1.1/pvp-specification.md). Is there anything else preventing this from being released to https://pvp.haskell.org/?

**Comment by fumieval** [comment]
It would be nice to roll out the new PVP sooner than later. Is there any blocker?

**Comment by Bodigrim** [comment]
Ping?

**Comment by hasufell** [comment]
I don't see why this ticket should remain open. The fix has been committed. Whether or when to release pvp-1.1 is a different matter, no?
