### ISSUE TITLE
Trying to reach community consensus by focusing on the things that are uncontroversial

### ISSUE THREAD

**Issue by sol** [haskell/pvp#21]
There have been a lot of controversies over the PVP in the past and at least from my perspective **the PVP does not represent community consensus**.

What prevented me in the past from giving any further input on the PVP is that some of the things it specifies are controversial in nature and people can have different valid opinions about specific aspects.  Which gave me a feeling of "unresolvable, nothing to achieve here".

But how about we focus, instead of trying to resolve this controversies, on the things were we do have actual community consensus and remove the controversial parts?

Yes, it would be less detailed, yes it would leave things unspecified; **BUT**, wouldn't that still be better than some document that effectively splits the community?

With any given controversy it is often possible to reach consensus by taking a step back and focusing on the things were it's easy to agree on.

Worst case scenario: Nothing changes.
Best case scenario: We make the PVP something that helps us foster a sense of community.

**Comment by hvr** [comment]
The purpose of the [PVP](http://pvp.haskell.org/) specification (c.f. [PVP FAQ](https://pvp.haskell.org/faq/)) is to

> inform clients of a package of changes to that package that might affect them, and to provide a way for clients to specify a particular version or range of versions of a dependency that they are compatible with. 

discussion here should focus only on how to live up to that goal.

**Comment by bergmark** [comment]
Thanks @sol,

I think it would be great to have a subset of the PVP that e.g. stackage could recommend maintainers to use. Do you have ideas on how and where this conversation should take place?

**Comment by hvr** [comment]
@bergmark I strongly recommend to call such a Stackage specific versioning policy clearly different than the proper PVP we promote on Hackage to avoid confusion and resulting conflicts; an obvious candidate would be "SVP".

**Comment by sol** [comment]
Well, I'm neither a `stack` nor Stackage user, for that reason alone I'm not very interested to work on Stackage specific policies.

@hvr I'm still not exactly sure how I should understand your reaction to this issue?

Does it mean:

> Yes, I acknowledge, the PVP does not represent community consensus.  But this does not matter, as it is a Hackage specific policy.  If you don't like that policy simply don't use Hackage.

?

**Comment by hvr** [comment]
@sol Sorry, I have no interest in an argument. My stance is captured in https://github.com/haskell/pvp/issues/21#issuecomment-360197683

**Comment by gbaz** [comment]
We will also need to have a discussion on the pvp as part of advancing and
codifying the semantics of ^>= and such. I would hope that such a
discussion would be a good place to draw in input. But the goal should be
primarily meeting a technical bar - and it would be good to codify that bar
(something like “accurate representation of build constraints”) - and
within that goal there’s a secondary question of making it as pleasant as
possible to do so.

A discussion about a policy that doesn’t put that bar foremost is a fine
discussion, but yeah, its about something with a different purpose than the
pvp.

**Comment by gbaz** [comment]
One more comment - the relationship of hackage to the pvp (or other
versioning policies) is an ecosystem question we should tackle, but
elsewhere. The pvp itself isn’t “hackage specific” - rather it is a general
purpose policy for haskell versioning with a specified goal. Hackage simply
happens to encourage it.
