### ISSUE TITLE
Decision tree diagram recommends misleading version numbers

### ISSUE THREAD

**Issue by gwils** [haskell/pvp#25]
When a major version bump is necessary, the decision tree diagram recommends
`A . B . C` -> `A . (B+1) . C` or `(A+1) . B . C`

To me it would be more sensible to recommend something like

`A . B. C` -> `A . (B+1) . C'` or `(A+1) . B' . C'`

since typically (although not necessarily) the lower version components will change to become zero, rather than staying the same as the former implies.

**Comment by hvr** [comment]
I believe this was already addressed by #20 (which hasn't been deployed yet). Can you confirm whether the change in #20 is sufficient to address your concern?

**Comment by gwils** [comment]
It is sufficient. Thanks!
