### ISSUE TITLE
Document differences with SemVer

### ISSUE THREAD

**Issue by hvr** [haskell/pvp#5]
Many people already know about SemVer, so it may make sense to add a section explaining how PVP relates to SemVer, and what the commonalities and differences with SemVer are.

**Comment by tfausak** [comment]
The [SemVer section of the FAQ](http://pvp.haskell.org/faq/#semver) addresses this. Is it missing anything?

**Comment by hvr** [comment]
initially I was wondering about adding a short mention along the lines of "beware, PVP is significantly different from SemVer" at the top of the PVP; but since then the FAQ came to be, and I guess it's good enough for now. So let's consider this one done.
